Adding support for labels
gdbots/schemas pull request #41
Opened 2020-07-14 02:05 UTC by rsumilang

2020-07-15 04:30 UTC, gdbrown requested changes

2020-07-15 04:30 UTC, gdbrown commented on schemas/gdbots/ncr/command/update-labels/latest.xml
> +      <field name="add_labels" type="string" rule="list" required="true"/>
@rsumilang make this `rule="set"` and should we do a pattern on these?  should not be required.

2020-07-15 04:30 UTC, gdbrown commented on schemas/gdbots/ncr/command/update-labels/latest.xml
> +      <field name="remove_labels" type="string" rule="list" required="true" overridable="true"/>
@rsumilang should not be required, a set, no overridable

2020-07-15 04:30 UTC, gdbrown commented on schemas/gdbots/ncr/event/labels-updated/latest.xml
> +      <field name="labels_updated" type="string" rule="list" required="true"/>
@rsumilang labels_added instead of updated for the field name.  rule is set, not required.

2020-07-15 04:30 UTC, gdbrown commented on schemas/gdbots/ncr/event/labels-updated/latest.xml
> +      <field name="old_etag" type="string" pattern="^[\w\.:-]+$" max="100"/>
@rsumilang we don't really need new and old/etag here.

2020-07-15 04:30 UTC, gdbrown commented on schemas/gdbots/ncr/event/labels-updated/latest.xml
> +      <curie-major>gdbots:common:mixin:labelable:v1</curie-major>
@rsumilang the event/command itself is not labelable.  taggable sure, but not labelable.

2020-07-15 04:30 UTC, gdbrown commented on schemas/gdbots/common/mixin/labelable/1-0-0.xml
> +          Labels is a list that categorizes data or tracks references in
@rsumilang should be a set and we probably should constrain the format.  maybe `[\w-]`.  rather than `ANy^T%h&ng*@!?`

2020-07-15 04:30 UTC, gdbrown commented on schemas/gdbots/common/mixin/labelable/1-0-0.xml
> +          Labels is a list that categorizes data or tracks references in
@rsumilang has search indexing implications when needing fulltext vs exact match (which any field with a pattern is automatically a term/exact match search)

2020-07-15 16:42 UTC, rsumilang commented
@gdbrown this has been udpated

2020-07-17 19:21 UTC, gdbrown approved these changes

2020-07-17 19:21 UTC, merged